[package]
name = "bouncydvd"
version = "0.1.0"
authors = ["Nikhil Jha <hi@nikhiljha.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.16.0"
